---

- name: CFME | Gather facts
  hosts: all
  gather_facts: true

- name: CFME | Setup primary DB
  hosts: cfme_vmdb_pri
  become: true
  gather_facts: false
  vars_files:
    - "group_vars/cloudforms"
    - "group_vars/vault"
  roles:
    - cfme-pri-db-create 

- name: CFME | Join Non Database appliances to the region
  hosts: cfme_app
  become: true
  gather_facts: false
  vars_files:
    - "group_vars/cloudforms"
    - "group_vars/vault"
  roles:
    - cfme-join-region

- name: CFME | Setup database replication
  hosts: cfme_vmdb_sec
  become: true
  vars_files:
    - "group_vars/cloudforms"
    - "group_vars/vault"
  roles:
    - cfme-sec-db-create

- name: CFME | perform generic configuration on the appliances
  hosts: cfme_vmdb_pri,cfme_app
  become: true
  gather_facts: false
  vars_files:
    - "group_vars/cloudforms"
    - "group_vars/vault"
  roles:
    - cfme-generic

- name: CFME | CloudForms Essentials Install
  hosts: cfme_vmdb_pri,cfme_app 
  gather_facts: false
  become: true
  vars:
    dest_dir: /root/
    github_user: ramrexx
    cfme_base_dir: "{{ dest_dir }}CloudForms_Essentials"
    rht_base_dir: "{{ dest_dir }}cfme-rhconsulting-scripts"
  roles:
    - cfme-essentials

- name: CFME | Setup Providers and services
  hosts: cfme_app[0]
  gather_facts: true 
  vars_files:
    - "group_vars/cloudforms"
    - "group_vars/vault"
  roles:
    - cfme-providers
    - cfme-services
