---

- name: CFME | essentials | Clone cfme-rhconsulting-scripts
  git:
    repo: https://github.com/rhtconsulting/cfme-rhconsulting-scripts.git
    dest: "{{ rht_base_dir }}"
  tags:
   - essentials

- name:  CFME | essentials | Install the cfme-rhconsulting-scripts
  shell: make clean install
  args:
    chdir: "{{ rht_base_dir }}"
  tags:
   - essentials

- name: CFME | essentials | Clone CloudForms_Essentials
  git:
    repo: "https://github.com/{{ github_user }}/CloudForms_Essentials.git"
    dest: "{{ cfme_base_dir }}"
  tags:
   - essentials

- name: CFME | essentials | Import automate domain
  shell: miqimport domain CloudForms_Essentials "{{ cfme_base_dir }}/automate"
  args:
    chdir: "{{ cfme_base_dir }}"
  tags:
   - essentials

- name: CFME | essentials | Import dialogs
  shell: "miqimport service_dialogs service_dialogs/"
  args:
    chdir: "{{ cfme_base_dir }}"
  tags:
   - essentials

- name: CFME | essentials | Import buttons
  shell: "miqimport buttons buttons/"
  args:
   chdir: "{{ cfme_base_dir }}"
  tags:
   - essentials

- name: CFME | essentials | Import alerts
  shell: "miqimport alerts alerts/"
  args:
   chdir: "{{ cfme_base_dir }}"
  tags:
   - essentials

- name: CFME | essentials | Import policies
  shell: "miqimport policies policies/"
  args:
   chdir: "{{ cfme_base_dir }}"
  tags:
   - essentials

- name: CFME | essentials | Import reports
  shell: "miqimport reports reports/"
  args:
   chdir: "{{ cfme_base_dir }}"
  tags:
   - essentials

- name: CFME | essentials | Import widgets
  shell: "miqimport widgets widgets/"
  args:
   chdir: "{{ cfme_base_dir }}"
  tags:
   - essentials

